CREATE TABLE "instruments" (
	"symbol" text PRIMARY KEY NOT NULL,
	"instrument_type" text NOT NULL,
	"currency" text NOT NULL,
	"timezone" text NOT NULL,
	"exchange_timezone_name" text NOT NULL,
	"long_name" text,
	"short_name" text,
	"exchange_name" text NOT NULL,
	"full_exchange_name" text,
	"first_trade_date" timestamp,
	"has_pre_post_market_data" boolean DEFAULT false,
	"chart_previous_close" real,
	"regular_market_price" real NOT NULL,
	"regular_market_day_high" real,
	"regular_market_day_low" real,
	"regular_market_volume" real,
	"fifty_two_week_high" real,
	"fifty_two_week_low" real,
	"pre_market_start" timestamp,
	"pre_market_end" timestamp,
	"regular_market_start" timestamp,
	"regular_market_end" timestamp,
	"post_market_start" timestamp,
	"post_market_end" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
